using Documenter

# include("preprocess.jl")

# download latest changelog
# download("https://raw.githubusercontent.com/julia-vscode/julia-vscode/main/CHANGELOG.md", joinpath(@__DIR__, "src", "changelog.md"))
# download package.json so we can generate an overview over keybindings/commands/...
# download("https://raw.githubusercontent.com/julia-vscode/julia-vscode/main/package.json", joinpath(@__DIR__, "src", "package.json"))

# generate_keybindings()

makedocs(
    sitename = "VS Code中的Julia插件",
    pages = [
        "主页" => "index.md",
        # "Setup" => "setup.md",
        "入门指南" => "gettingstarted.md",
        "常见问题" => "faq.md",
        "用户指南" => Any[
            "代码运行"=>"userguide/runningcode.md",
            "快捷键与命名"=>"userguide/keybindings.md", # auto-generated by generate_keybindings
            "Julia环节"=>"userguide/env.md",
            "代码导航"=>"userguide/codenavigation.md",
            "代码编辑"=>"userguide/editingcode.md",
            "代码格式化"=>"userguide/formatter.md",
            "绘图"=>"userguide/plotgallery.md",
            "表格查看"=>"userguide/grid.md",
            # "Understanding Code" => "userguide/understandingcode.md",
            "代码检查器"=>"userguide/linter.md",
            "代码分析"=>"userguide/profiler.md",
            # "Tasks" => "userguide/tasks.md",
            "调试"=>"userguide/debugging.md",
            "Weave Markdown文档"=>"userguide/weave.md",
            "远程"=>"userguide/remote.md",
            "测试项框架"=>"userguide/testitems.md"
            # "Settings" => "userguide/settings.md"
        ],
        # "Change Log" => "changelog.md",
        "发展者文档" => Any[
            "概况"=>"devdocs/devdocs.md"
        ]
    ],
    remotes = nothing,
    format = Documenter.HTML(
        prettyurls = ("CI" in keys(ENV))
    )
)

# deploydocs(
#     repo = "github.com/julia-vscode/docs";
#     push_preview = true
# )
